title VICTOR Technologies, Inc. (c)1983  Universal Boot (Net/Hard/Floppy)
page 60,132
; ***********************************************************************
; *                                                                     *
; *  Proprietary Rights Notice:   All rights  reserved.  This material  *
; *  contains  the   valuable   properties   and   trade  secrets   of  *
; *  Victor Technologies, Inc.  (VICTOR)                                *
; *  of  Scotts Valley,  California,  USA.                              *
; *  embodying   substantial   creative   efforts   and   confidential  *
; *  information, ideas,  and  expressions;  no part of  which  may be  *
; *  reproduced or transmited in any form or by any means; electronic,  *
; *  mechanical, or otherwise;  including  photo copying and recording  *
; *  or  in  connection  with  any  information  storage or  retrieval  *
; *  system  without the permission  in writing  from VICTOR.           *
; *                                                                     *
; *  Copyright notice:  Copyright (C) 1983                              *
; *                                                                     *
; *  An unpublished work by:                                            *
; *                                                                     *
; *                  Victor Technologies, Inc.                          *
; *                  380 El Pueblo Road                                 *
; *                  Scotts Valley, California 95066                    *
; *                                                                     *
; ***********************************************************************/
page
